### ISSUE TITLE
Worker panicked if connection reset by peer

### ISSUE THREAD

**Issue by zonyitoo** [zonyitoo/coio-rs#1]
```
thread '<main>' panicked at 'Error occurs: Error { repr: Os { code: 54, message: "Connection reset by peer" } }', /Users/zonyitoo/Projects/coio/examples/tcp-echo-server-limited.rs:64
thread '<unnamed>' panicked at 'Error occurs: Error { repr: Os { code: 54, message: "Connection reset by peer" } }', /Users/zonyitoo/Projects/coio/examples/tcp-echo-server-limited.rs:64
thread '<unnamed>' panicked at 'Error occurs: Error { repr: Os { code: 54, message: "Connection reset by peer" } }', /Users/zonyitoo/Projects/coio/examples/tcp-echo-server-limited.rs:64
thread '<main>' panicked at 'Error occurs: Error { repr: Os { code: 54, message: "Connection reset by peer" } }', /Users/zonyitoo/Projects/coio/examples/tcp-echo-server-limited.rs:64
stack backtrace:
thread '<unnamed>' panicked at 'Error occurs: Error { repr: Os { code: 54, message: "Connection reset by peer" } }', /Users/zonyitoo/Projects/coio/examples/tcp-echo-server-limited.rs:64
   1:        0x10d83c440 - sys::backtrace::write::h6000c312610142aew8r
thread '<unnamed>' panicked at 'Error occurs: Error { repr: Os { code: 54, message: "Connection reset by peer" } }', /Users/zonyitoo/Projects/coio/examples/tcp-echo-server-limited.rs:64
thread '<unnamed>' panicked at 'Error occurs: Error { repr: Os { code: 54, message: "Connection reset by peer" } }', /Users/zonyitoo/Projects/coio/examples/tcp-echo-server-limited.rs:64
thread '<unnamed>' panicked at 'Error occurs: Error { repr: Os { code: 54, message: "Connection reset by peer" } }', /Users/zonyitoo/Projects/coio/examples/tcp-echo-server-limited.rs:64
   2:        0x10d83f799 - panicking::on_panic::h5ba6699237c7b4d5NKw
   3:        0x10d832df2 - rt::unwind::begin_unwind_inner::h4aca1755d37f737c0fw
   4:        0x10d83345d - rt::unwind::begin_unwind_fmt::h1bdaeee21161054d6ew
   5:        0x10d78879a - rt::unwind::try::try_fn::h2379474388515555596
   6:        0x10d83efa8 - __rust_try
   7:        0x10d83bc40 - rt::unwind::try::inner_try::hd8216b9fe11fca4cTbw
   8:        0x10d788ac3 - boxed::F.FnBox<A>::call_box::h3910618379480855939
   9:        0x10d79b7bf - coroutine::coroutine_initialize::hf427719d2d249c9bNyc
thread panicked while panicking. aborting.
```

**Comment by zonyitoo** [comment]
Minimal test case
```rust
extern crate coio;

use coio::Scheduler;

fn main() {
    Scheduler::new().with_workers(2).run(|| {
        loop {
            Scheduler::spawn(|| {
                Scheduler::sched();
                panic!("Just panic!");
            });
        }
    }).unwrap();
}
```

This program will print out

```
thread 'Worker 1' panicked at 'Just panic!', examples/loop_panic.rs:10
thread 'Worker 1' panicked at 'Just panic!', examples/loop_panic.rs:10
stack backtrace:
   1:        0x1036a0888 - sys::backtrace::tracing::imp::write::hce2f1d7df9a6ac6eW5s
   2:        0x1036a204f - panicking::log_panic::closure.38916
   3:        0x1036a1af9 - panicking::log_panic::hb9569ec1e39cdd527Uw
   4:        0x1036989f4 - sys_common::unwind::begin_unwind_inner::haeffb18d8a0216a0u8r
   5:        0x103615ca7 - sys_common::unwind::begin_unwind::h299509344594415806
   6:        0x10364375e - main::closure.7655
   7:        0x1036435f2 - scheduler::Scheduler::spawn_opts::closure.7652
   8:        0x1036435cd - try::closure.7649
   9:        0x1036433a7 - thread::catch_panic::closure.7645
  10:        0x103643389 - sys_common::unwind::try::try_fn::h11047726112562185057
  11:        0x10369fd58 - __rust_try
  12:        0x10369de3e - sys_common::unwind::try::inner_try::h5efc4bb9f1eaef3c24r
  13:        0x103643340 - sys_common::unwind::try::h8731999042205468625
  14:        0x10364319d - thread::catch_panic::h17773043214844242791
  15:        0x10364313b - try::h16045251145919867838
  16:        0x10364306a - scheduler::Scheduler::spawn_opts::closure.7642
  17:        0x103644a1c - boxed::F.FnBox<A>::call_box::h12398177750358903531
  18:        0x10366db1b - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h10680920054568869059
  19:        0x10366d9a7 - coroutine::coroutine_initialize::__rust_abi
  20:        0x10366d93c - coroutine::coroutine_initialize::he3e5684adeeeb7baobc
thread panicked while panicking. aborting.An unknown error occurred
```

Still wondering why it said "thread panicked while panicking."

**Comment by zonyitoo** [comment]
Bug does not exists in the latest commit.
