### ISSUE TITLE
Panic when using coio::sleep_ms

### ISSUE THREAD

**Issue by panicbit** [zonyitoo/coio-rs#14]
rev: 8d3f9fa03a356286

The following program panics and outputs

```
Routine 1: 0
Routine 2: 1
thread 'Worker 0' panicked at 'Box<Any>', coio-rs/src/runtime/processor.rs:484
thread 'Worker 0' panicked at 'Box<Any>', coio-rs/src/runtime/processor.rs:484
```

```rust
extern crate coio;
use coio::{spawn, Scheduler};

fn main() {
    Scheduler::new().with_workers(1).run(move|| {

        spawn(move || {
            for i in 0..10 {
                if i % 2 == 0 {
                    println!("Routine 1: {}", i);
                    coio::sleep_ms(2000);
                }
            }
        });

        spawn(move || {
            for i in 0..40 {
                if i % 2 != 0 {
                    println!("Routine 2: {}", i);
                    coio::sleep_ms(500);
                }
            }
        });

    });
}
```

**Comment by zonyitoo** [comment]
Well, this panic with `Box<Any>` is because the main function is already exited and going to force all spawned children to unwind the stack. So this behavior is absolutely correct.

You must use `.join()` to keep the main function waiting until all the spawned coroutines exit.

**Comment by panicbit** [comment]
I see, thanks.
